# Generated by Django 5.1.4 on 2024-12-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petfood',
            name='foodDesc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
