# Generated by Django 5.1.4 on 2024-12-30 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_petfood_fooddesc'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetFoodDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('expiryDate', models.DateField()),
                ('petFood', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='myapp.petfood')),
            ],
        ),
    ]
