# Generated by Django 5.1.4 on 2024-12-31 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_petfooddetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petfooddetails',
            name='petFood',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.petfood'),
        ),
    ]
