# Generated by Django 5.1.4 on 2025-01-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_pet_petfood_pet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custId', models.IntegerField()),
                ('custName', models.CharField(max_length=100)),
                ('custEmail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='petvaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccineName', models.CharField(max_length=100)),
                ('pet', models.ManyToManyField(to='myapp.pet')),
            ],
        ),
    ]
