# Generated by Django 5.1.4 on 2025-01-01 08:25

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_customer_petvaccine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='custEmail',
            field=models.CharField(max_length=200, validators=[myapp.models.validation_Email]),
        ),
    ]
