# Generated by Django 5.1.4 on 2025-01-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_customer_custemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petfood',
            name='foodDesc',
            field=models.TextField(null=True),
        ),
    ]
