# Generated by Django 5.1.4 on 2025-01-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_petfood_fooddesc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petfood',
            name='foodDesc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
