# Generated by Django 5.1.4 on 2025-01-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_petfood_fooddesc'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='custContact',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
