# Generated by Django 5.1.4 on 2025-01-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_customer_custcontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodName', models.CharField(max_length=100)),
                ('prodDesc', models.TextField()),
                ('prodPrice', models.DecimalField(decimal_places=2, max_digits=7)),
                ('prodImage', models.ImageField(upload_to='images/')),
                ('prodRating', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
    ]
