# Generated by Django 5.1.4 on 2025-01-17 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_cart_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='uid',
        ),
    ]
