# Generated by Django 5.1.4 on 2025-01-30 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_customerdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customerDetails',
        ),
    ]
